### ISSUE TITLE
Can the hidden server access the ESNI private key?

### ISSUE THREAD

**Issue by huitema** [kazuho/draft-kazuho-quic-authenticated-handshake#2]
The ESNI procedure involve the client, the fronting server and the hidden server. The client gets the ESNI public key, and uses it to encrypt the "real SNI". The fronting server decrypts the ESNI using the corresponding private key, obtains the "real SNI", and forwards the connection to the hidden server. There is no need for the hidden server to know the private ESNI key. If there was such a need, all services that share the fronting server would need to know the key, which would greatly increase the risks of leak.

The spec computes the AAD as:
```
   initial_auth_secret = HKDF-Expand-Label(Zx, "quic initial auth",
                                           Hash(ESNIContents), 16)
```
This requires access to the ESNI content. This is not a problem for the client because it chose that content, but it is not obvious for the hidden server, which does not have access to the ESNI private key. How is that supposed to work?

**Comment by kazuho** [comment]
Admittedly, this is an issue. You would need some kind of coordination (e.g., the fronting server sending the ESNI shared secret to the backend server along with the Initial packet).

However, I am not sure if I care about the issue, for the following two reasons:
* It's a rare-case anyways, and we do not need to support all the use-cases.
* I am not sure if we would be able to keep support for split-server approach in ESNI itself.
* Security-wise, using QUIC in split-server approach has worse properties that TCP, because all the communication happens end-to-end. For example, if you have a big one-way flow, it would expose the latency between the client and the hidden server, whereas in case of TCP what was exposed was the latency between the client and the fronting server.

**Comment by kazuho** [comment]
PS. I forgot the fact that _it is impossible to have an uncoordinated middlebox that lets the server-side tuple being shared between multiple servers_ (in this case hidden servers). This is because the middlebox cannot identify the mapping of the connection when either of the endpoints starts using a new Connection ID mid-connection.

Therefore, **it is impossible to support split server mode in QUIC**. At least, it is meaningless because the middlebox needs to allocate dedicated port for each hidden server (and that essentially exposes to which hidden server the client is connecting).

**Comment by huitema** [comment]
@kazuho yes, it probably is impossible to support the split server mode today. But this is a bug, not a feature. We should not use that as a design guideline.

**Comment by kazuho** [comment]
@huitema No. It is a feature. It's a win in terms of privacy, because an observer cannot track the lifetime of each of the multiple connections that share the same 5-tuple. I think that is more important than supporting split mode.

**Comment by huitema** [comment]
Fine. A given 5 tuple will link a single client to a single server. But that still does not answer my question. The ESNI private key is known to the fronting server -- e.g., the CDN. The ESNI content is then not known by the hidden server, not unless we make some other assumption. That assumption needs to be spelled out.

**Comment by kazuho** [comment]
I can add that to the Considerations section. Does than sound OK to you?

**Comment by huitema** [comment]
Yes, that's probably what we want. Explain that this only works if the fronting server somehow passes the ESNI content to the hidden server.

**Comment by kazuho** [comment]
Thanks! I've added a subsection in c0d81ae. Please let me know what you think.

**Comment by kazuho** [comment]
My understanding is that we are doing a follow up on this issue in #11.
